language: generic
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIAJKPI5ATLCSAJ54TQ
  secret_access_key:
    secure: mebqsEGJqo7RecSq0KV3JDFqYomUEP6j1NbwdMWO/TRZ7QfN3E1NpawBNu4sIJ2Hszw7VM+Utr2IBXJJxnQFe4FQndfGprMCkM3EY3RFzqVkz6Dp+RkSNQYpVYYZ2K5sKEw/lVL5WdRupSjdlf6YwO9SNOBydwrbFOwxw7GVV8P+/Ly+Ek0xAwinFC3BD1eukLLFBmWOtKs/U1xyYbKyiBHtiulaKOPwGPN1T1rAffDO42EFJ2MkgpzOBNACXlyC/f8znUO53nU9Fpajjc+Jw9D34aFd5y39AWwyXp/+Ivj8zk2uTjjFvX5Y+uDYXvovusFIiQokcqSaaIWv2sXVHpevvP0jp4cwt3PUr2ho3hPQvc65UvGS2c6R2joDqucYz60qfyRWlEe8PZpv5fFGrTO8mPwGv0XfL1/1pyqYdT75+xx6gPeNesfriii86SnDZpfsRgU6o1vwVd9mcMBb+rMG9l48j7eZmtB3B8d6nPNbkF+J/jx+afSY3KD0zROZLGTzC0pxzN/hvcXOjiXVHXk+5J6uIlYRlDhJdcHqBciwnjeVCD63K9+gvcXUYGJa+CbeOoEHCptQCII2WfU35AwecTh8ipv9C5U7RWQQt82bxKcK3CjkTGwOjs0Kh5SlYkQv9HF9meM2RiWH6gNdBfghrRpgOKOYQ63CVRqnAbc=
  bucket: "alldredgecraigseniorproject"
  on:
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
