language: generic
before_deploy:
- pip install -r src/requirements.txt -t skill-env
- cp -r src/* skill-env/
- cd skill-env/
- zip -r ../skill.zip *
- cd ..
deploy:
- provider: lambda
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_key
  function_name: "oralHistory"
  zip: skill.zip
  region: "us-east-1"
  role: "arn:aws:iam::523059797638:role/service-role/oral_history"
  runtime: "python2.7"
  module_name: "oralHistory"
  handler_name: "handler"
  on:
    branch: master
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
- provider: lambda
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_key
  function_name: "oralHistoryDev"
  zip: skill.zip
  region: "us-east-1"
  role: "arn:aws:iam::523059797638:role/service-role/oralHistoryDevRole"
  runtime: "python2.7"
  module_name: "oralHistory"
  handler_name: "handler"
  on:
    branch: dev
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
