deploy:
  provider: s3
  access_key_id: AKIAI7F3MP5K3BNFHE5Q
  secret_access_key:
    secure: lcx4WkvEEjiDLscSfp1X6oRBSLRxzbK0qt1XKxO19zjkSB5d2sFvh9SCfMAY3POoBOKO8YNGkykVa7VHoJS4VNZmTaBZi9KHkvjpjNua2Q6aHG48+0CJQtgtkkIBDXwCUCUKy2aBktjzJAvZ3k+33XeqfjxwvFR5thS4uM+/xVgmNhxxcshoAoHyohsP6NsIdFd1yADsCZUf9jyn4BdMCGXj5DSWUOlChKdHkdPtv7Mmm5OaDZhIiGJWZFNmB8j+DuiXYlK/3RhSCN0f4tgUEaBczK228KI9isiLoBEo9B91vPK3Q9WilnSrhbcuAqZcRkSpd8jheYvTqyQHuEUg0lMmgqmMaXhojzA3XGwNuxdOvzVY9Nax24d3Ib2UuwjvStRy+gXIncH3n1pqz6Em0uuGXDfwLhai/c2bBXW8AUa2gM9KW/sF6T0Av5htzC17RAwKCVERuzzxB6Hd9LrmUWMqB+sCxv3dPAW1J2S/aqDxNU1xodpqeGR2JhAN3bfMmxKfwOjM16cpgH2Yb0oQTPHH3Vi3vUDX2FbJA5balUf8Fd3gm4hDEJo+Ut5mo3YDinwsjYQRZBqH99HqjlZ6jcA9UJAmZhSk8WaEjJpa8TevWQbb0lzpBEq+fNt7AB+qf+CweD/2eqqtQLHbH/NcbNU4JWyk7H3tOqbc0DYrTyw=
  bucket: alldredgecraigseniorproject
  acl: ''
  on:
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
