language: generic
before_deploy:
- zip -j oral_history.zip src/oralHistory.py
deploy:
- provider: s3
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_key
  bucket: alldredgecraigseniorproject
  local-dir: src
  upload-dir: src
  region: us-east-1
  on:
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
- provider: lambda
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_key
  function_name: "oralHistory"
  zip: oral_history.zip
  region: "us-east-1"
  role: "arn:aws:iam::523059797638:role/service-role/oral_history"
  runtime: "python2.7"
  module_name: "oralHistory"
  handler_name: "lambda_handler"
