language: generic
deploy:
  provider: s3
  access_key_id: $s3_access_key_id
  secret_access_key: $s3_secret_key
  bucket: alldredgecraigseniorproject
  local-dir: src
  upload-dir: src
  region: us-east-1
  on:
    repo: AlldredgeCraigSeniorProjectTeam/oral-history
